// inscriptions.ts — GENERATED by cessation/sync-tracker.mjs. Do not edit by hand.
//
// Regenerate with:  cd ../cessation && node sync-tracker.mjs --write
//
// Every value here was read from the chain: children from the engine's /r/children,
// hashTail and inscriptionUnix from each piece's own CBOR metadata decoded with the
// ENGINE's decoder, blockHeight from ord. Nothing is transcribed by hand, because
// hand-maintained copies of on-chain data are how this project's notes went stale.
//
// Generated 2026-09-21T05:59:37.349Z — 31 of 31 pieces inscribed.

export interface PieceInscription {
  inscriptionId: string;
  hashTail: number;        // 0–99
  inscriptionUnix: number; // Unix seconds
  blockHeight: number;     // block the reveal confirmed in
  sat: number;             // the rare sat this piece lives on
}

// Index matches piece index. null = not yet inscribed.
export const PIECE_INSCRIPTIONS: (PieceInscription | null)[] = [
  { inscriptionId: "35e961c5f4003a9e064db70e6d1c55b7314ce4b38413d3d93a32b116c748122fi0", hashTail: 40, inscriptionUnix: 1789929203, blockHeight: 967879, sat: 12425429610010 }, // piece 00 — 2018-07-16
  { inscriptionId: "2aded0d84c356bf5ee5744c202a578c147539a7cccec3d02093a4c927bfa1e41i0", hashTail: 36, inscriptionUnix: 1789940435, blockHeight: 967901, sat: 12425429610011 }, // piece 01 — 2018-10-04
  { inscriptionId: "1dd7ee63e1945eb8e34707cfbd8b86715984d80678ee7a469c266f5bf9b97a55i0", hashTail: 39, inscriptionUnix: 1789942703, blockHeight: 967905, sat: 12425429610012 }, // piece 02 — 2019-01-24
  { inscriptionId: "08c2b5271c5c9f9aeefcc6fe977f74f36bcad72584564c0eca7626d9bc04a082i0", hashTail: 66, inscriptionUnix: 1789943879, blockHeight: 967908, sat: 12425429610013 }, // piece 03 — 2019-04-24
  { inscriptionId: "a5f3984fa55d3e6c1d829d2284b5f0232b3a499f1e63bc44430bdb06d56365b4i0", hashTail: 12, inscriptionUnix: 1789944556, blockHeight: 967912, sat: 12425429610014 }, // piece 04 — 2019-07-31
  { inscriptionId: "3e8388adb03d81a1582a8e081ab01c047bdb8be7833d4a42f13589e2073848b0i0", hashTail: 12, inscriptionUnix: 1789949119, blockHeight: 967915, sat: 12425429610015 }, // piece 05 — 2020-02-07
  { inscriptionId: "4df18c747f730fd37d5a3db9e7dccf547e4cba239a2bdd24d9deaff49b3ffdb1i0", hashTail: 49, inscriptionUnix: 1789953998, blockHeight: 967919, sat: 12425429610016 }, // piece 06 — 2020-02-28
  { inscriptionId: "1fad9d4589518af9bf7ee86d7837df76521f14be22d3101a688b14b8d846f805i0", hashTail: 47, inscriptionUnix: 1789954820, blockHeight: 967920, sat: 12425429610017 }, // piece 07 — 2020-03-13
  { inscriptionId: "35560c7ebe7a9e75414b5c0d033b80b26d294c4fcabee927ce84cc93b69d68e5i0", hashTail: 46, inscriptionUnix: 1789955335, blockHeight: 967921, sat: 12425429610018 }, // piece 08 — 2020-05-22
  { inscriptionId: "88ad624d0bab2cd4a8a5ae4ac79449a0e7846c2907aaac2c16b0b8d046108066i0", hashTail: 55, inscriptionUnix: 1789955821, blockHeight: 967922, sat: 12425429610019 }, // piece 09 — 2020-08-11
  { inscriptionId: "4deca53568108cdea23e3eb1eb0e31ce3c55d64bb80f53f57ce17b56da5215f5i0", hashTail: 44, inscriptionUnix: 1789955907, blockHeight: 967924, sat: 12425429610020 }, // piece 10 — 2020-11-12
  { inscriptionId: "7cd937b09413284705bb1731ee379869d20477580a9dd3c84ac74f098035af5di0", hashTail: 45, inscriptionUnix: 1789956098, blockHeight: 967925, sat: 12425429610021 }, // piece 11 — 2021-02-24
  { inscriptionId: "c0c56b70d246ddc44fce003e622b7cb20b96bbaa76a49c8b499a4321924f2adai0", hashTail: 24, inscriptionUnix: 1789956324, blockHeight: 967930, sat: 12425429610022 }, // piece 12 — 2021-09-01
  { inscriptionId: "2e61d8c0f83a79204443c1478536e104607b44ff4ac36cbd523b3caf10d9379fi0", hashTail: 18, inscriptionUnix: 1789961152, blockHeight: 967931, sat: 12425429610023 }, // piece 13 — 2021-12-01
  { inscriptionId: "747c36301c9c6d35dede93a4c79585558adb176e1770fb6616ceacf43268c103i0", hashTail: 35, inscriptionUnix: 1789961685, blockHeight: 967932, sat: 12425429610024 }, // piece 14 — 2022-02-14
  { inscriptionId: "04013d7631936a47c7953712c07edc9eb0b3f0fc84f4760ad1b1789da279934ei0", hashTail: 59, inscriptionUnix: 1789962147, blockHeight: 967933, sat: 12425429610025 }, // piece 15 — 2022-05-13
  { inscriptionId: "b4615174fef4536f39f6b0307da7cda08755f35ca76da7ebd4ef8bc0b629a5eci0", hashTail: 76, inscriptionUnix: 1789962527, blockHeight: 967934, sat: 12425429610026 }, // piece 16 — 2022-08-25
  { inscriptionId: "8613cf254fa05cb45208c84d448d10096f622cb6685f8ccaad99f7a435b334e8i0", hashTail: 36, inscriptionUnix: 1789962607, blockHeight: 967935, sat: 12425429610027 }, // piece 17 — 2023-06-12
  { inscriptionId: "b960b347890805fadd0c51c16de143c392ed261f727c0f81bc0fe4c8e68f4ce0i0", hashTail: 44, inscriptionUnix: 1789963362, blockHeight: 967936, sat: 12425429610028 }, // piece 18 — 2023-09-05
  { inscriptionId: "155613aa15de498a3099a632df069be02f00e6bdd71a21dc2633e025d6bc4963i0", hashTail: 98, inscriptionUnix: 1789963781, blockHeight: 967937, sat: 12425429610029 }, // piece 19 — 2023-12-05
  { inscriptionId: "6ba57eb3f662a68c933836112f8a64f6c5c80918e147ac8a651fc40669067a5ai0", hashTail: 96, inscriptionUnix: 1789963941, blockHeight: 967939, sat: 12425429610030 }, // piece 20 — 2024-02-05
  { inscriptionId: "f85b32629fe4e2e67275d6a86aa57e4d4a0dfbd52a0e64338dfe8fa7b93d4584i0", hashTail: 68, inscriptionUnix: 1789964250, blockHeight: 967940, sat: 12425429610031 }, // piece 21 — 2024-06-10
  { inscriptionId: "6b1284313b2b1d8a272322f9c5f8304c8ec40bd1493a38da6e8b3e00b3e60d23i0", hashTail: 33, inscriptionUnix: 1789964421, blockHeight: 967942, sat: 12425429610032 }, // piece 22 — 2024-09-16
  { inscriptionId: "1af7edbde54d124454f95c3f4ea1c7df95bfdf8fcf18935b2bfb0376449a883ai0", hashTail: 69, inscriptionUnix: 1789966297, blockHeight: 967943, sat: 12425429610033 }, // piece 23 — 2024-12-30
  { inscriptionId: "6f54436e26406591be11924d1b10fcc8ce54395ddd7f8189a97f08947fc0e36di0", hashTail: 6, inscriptionUnix: 1789966533, blockHeight: 967944, sat: 12425429610034 }, // piece 24 — 2025-03-26
  { inscriptionId: "dfe1c4c3f532d90acc96ad3b6dc95b22723098e73e785e24f5ccb030c951998fi0", hashTail: 14, inscriptionUnix: 1789967697, blockHeight: 967945, sat: 12425429610035 }, // piece 25 — 2025-06-18
  { inscriptionId: "7773e4587582a087023de45c61f4ff3dce6d89bc8ceec55273542946cb2950edi0", hashTail: 25, inscriptionUnix: 1789968236, blockHeight: 967946, sat: 12425429610036 }, // piece 26 — 2025-09-12
  { inscriptionId: "11bd3cc8601a4e19d6242469ab82a30f1c0ae28555b59cc37fc9f08498c45f34i0", hashTail: 95, inscriptionUnix: 1789968358, blockHeight: 967947, sat: 12425429610037 }, // piece 27 — 2025-12-11
  { inscriptionId: "3583219f694bf00897ba471bc1338514ffe479ed1fb89799e7b9502820f8d938i0", hashTail: 14, inscriptionUnix: 1789968956, blockHeight: 967948, sat: 12425429610038 }, // piece 28 — 2026-03-20
  { inscriptionId: "cb3bed3a4c3e65c0e74fddac603ae1cfb70bcd2aa3e0fb99dc2a813a97e86d3bi0", hashTail: 24, inscriptionUnix: 1789969528, blockHeight: 967949, sat: 12425429610039 }, // piece 29 — 2026-06-19
  { inscriptionId: "40b914134170dc5f9220642eb3f4d0ea7cea5c18e7e39655560f08508251d044i0", hashTail: 97, inscriptionUnix: 1789969837, blockHeight: 967950, sat: 12425429610040 }, // piece 30 — 2026-09-18
];

export const ENGINE_INSCRIPTION_ID: string | null = "936f1fbe6eb8f3a88ca6b6efde96722124182518b2a713210dfcfdec06410f67i0";
